# Generated by superflore -- DO NOT EDIT
#
# Copyright 2019 Open Source Robotics Foundation

inherit ros_distro_${ROS_DISTRO}
inherit ros_superflore_generated

DESCRIPTION = "Test package, which uses things exported by osrf_testing_tools_cpp."
AUTHOR = "William Woodall <william@osrfoundation.org>"
HOMEPAGE = "https://wiki.ros.org"
SECTION = "devel"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://package.xml;beginline=10;endline=10;md5=12c26a18c7f493fdc7e8a93b16b7c04f"

ROS_CN = "osrf_testing_tools_cpp"
ROS_BPN = "test_osrf_testing_tools_cpp"

ROS_BUILD_DEPENDS = ""

ROS_BUILDTOOL_DEPENDS = " \
    cmake-native \
"

ROS_EXPORT_DEPENDS = ""

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

ROS_EXEC_DEPENDS = ""

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = " \
    osrf-testing-tools-cpp \
"

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
# Bitbake doesn't support the "export" concept, so build them as if we needed them to build this package (even though we actually
# don't) so that they're guaranteed to have been staged should this package appear in another's DEPENDS.
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS_${PN} += "${ROS_EXEC_DEPENDS}"

SRC_URI = "https://github.com/ros2-gbp/osrf_testings_tools_cpp-release/archive/release/dashing/test_osrf_testing_tools_cpp/1.2.1-1.tar.gz;downloadfilename=${ROS_SP}.tar.gz"
SRC_URI[md5sum] = "af7dcdee5e30b5ed8d7565952d4dff29"
SRC_URI[sha256sum] = "4fa0b71d3569062bd768992d3ad500af690ad95f3b53e327f0079297fad4b88c"
S = "${WORKDIR}/osrf_testings_tools_cpp-release-release-dashing-test_osrf_testing_tools_cpp-1.2.1-1"

ROS_COMPONENT_TYPE = "${@ros_distro__get_component_type('osrf-testing-tools-cpp', d)}"
ROS_BUILD_TYPE = "cmake"

# Allow the above settings to be overridden.
ROS_INCLUDES_TREE := "${@ros_superflore_generated__get_includes_tree('osrf-testing-tools-cpp', d)}"

# Since osrf-testing package was updated, the source path now is no longer consistent between the test and package, so dont include the changed .inc file
# include ${ROS_LAYERDIR}/${ROS_INCLUDES_TREE}/osrf-testing-tools-cpp/osrf-testing-tools-cpp_common.inc
# include ${ROS_LAYERDIR}/${ROS_INCLUDES_TREE}/osrf-testing-tools-cpp/osrf-testing-tools-cpp-${PV}_common.inc

include ${ROS_LAYERDIR}/${ROS_INCLUDES_TREE}/osrf-testing-tools-cpp/${BPN}.inc
include ${ROS_LAYERDIR}/${ROS_INCLUDES_TREE}/osrf-testing-tools-cpp/${BPN}-${PV}.inc

inherit ${ROS_COMPONENT_TYPE}_component
inherit ros_${ROS_BUILD_TYPE}
